### ISSUE TITLE
KivyInstaller fails(?) on Win 7 64

### ISSUE THREAD

**Issue by jerryasher** [KeyWeeUsr/KivyInstaller#12]
I tried KivyInstaller on Win 7 64. It looks like it failed. It is 4 hours later, and while aspects were apparently successful, kivy.bat is still running, but doing nothing.

Log in https://gist.github.com/jerryasher/83b0e26f27646fedd38dcaf11ec1fb7c

I was trying to install:

+ 64 bit Python 2.7
+ Local kivy, not global
+ not to register python extensions

KivyInstaller has been running 4 hours, when I ^C to terminate it says: Kivy was not installed properly.

32 bit Python 3.6 is already installed and in the system path.

**Comment by KeyWeeUsr** [comment]
Well, it appears that it was successfully installed, so I don't understand why would it print such a message. It might have something to do with canceling it manually(`^C`). Run `kivy.bat` in the same folder without any modifications to the file, it should fetch the configuration and launch properly. Then try this:

    python share\kivy-examples\demo\touchtracer\main.py

If it still doesn't work, remove the folder and reinstall with the latest installer.

**Comment by jerryasher** [comment]
Thanks for the response.

So I haven't touched it since last night when I terminated the script. Just now I did as you asked, Opened a cmd shell, visited the directory, ran kivy.bat, and just running kivy.bat brings me:

```Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Jerry>cd c:\kivy

c:\kivy>dir *.bat
 Volume in drive C has no label.
 Volume Serial Number is 8206-6FC3

 Directory of c:\kivy

05/05/2017  06:51 PM            27,551 kivy.bat
               1 File(s)         27,551 bytes
               0 Dir(s)  52,064,329,728 bytes free

c:\kivy>which python
/C/Python/Python36-32/python

c:\kivy>kivy.bat
find: '5.1': No such file or directory
###############################################################################
KivyInstaller v3.4
Author: KeyWeeUsr @ https://github.com/KeyWeeUsr

Report issues @ https://github.com/KeyWeeUsr/KivyInstaller/issues
###############################################################################
[KivyInstaller] Looking for config file...
[KivyInstaller] Config file not found, running installation...
64bit environment detected Create 32bit instead? y/n
```

**Comment by KeyWeeUsr** [comment]
```
dir *.bat
```

This returns only the `*.bat` files from the current folder, which obviously will be only `kivy.bat`. A more useful output would be from `dir` command only, but nevermind. Judging from the output of your previously pasted log, you had to reach [this](https://ci.appveyor.com/project/KeyWeeUsr/kivyinstaller/build/1.0.193/job/7smsr1wjr7by3945#L11432) point in the installation, therefore:

* python is installed
* kivy is installed

but the log when the script is launched says it can't find the config file because it didn't run [this part](https://github.com/KeyWeeUsr/KivyInstaller/blob/master/kivy.bat#L551). Well, let's try to fix that. Open some editor, create a new file `config.kivyinstaller` in the same folder as `kivy.bat` is and paste these inside:

```
cp=cp27m
cpwhl=cp27
stable=1
cp2=cp27
cp3=cp35
py3=3.5.2
arch=win_amd64
py2=2.7.13
pyversion=2.7.13
gstreamer=1
master=1.9.2
installkivy=1
shrtct=27
admin=0
```

Then try to launch the script again, it should fetch the config and proceed normally.

However, judging from this:

```
c:\kivy>which python
/C/Python/Python36-32/python
```

I believe you ran the script inside of Msys or Cygwin. Neither of them is tested, therefore I suggest you to open an [ordinary Windows shell](http://www.wikihow.com/Open-the-Command-Prompt-in-Windows) and launch the script then.

Also, if you by any chance got to the last part of my previous post and `removed the folder`, then just ignore the above part with the config file and proceed with the clean installation with an ordinary Windows shell.

**Comment by jerryasher** [comment]
I did do this in a real cmd shell, but it is certainly the case that in my path, various pythi as well as cygwin/bin come ahead of windows.

For now I am going to assume that's the issue and try again with a clean install and cygwin's path removed.

Thanks for the help.

**Comment by KeyWeeUsr** [comment]
Feel free to confirm back if it fixed the problem for you :)
