### ISSUE TITLE
Python 3.5+ non-admin installation leaves traces in registry

### ISSUE THREAD

**Issue by Ch3fk0ch88** [KeyWeeUsr/KivyInstaller#2]
Hi,
i got this error:
```
DISPLAY: 'GetPython3.5.2-amd64.exe' TYPE: DOWNLOAD STATE: TRANSFERRED
PRIORITY: NORMAL FILES: 1 / 1 BYTES: 30177896 / 30177896 (100%)
Transfer complete.
Installing...
Python is installed
Installing pip...
Der Befehl "python" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Preparing Python for Kivy...
Der Befehl "python" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Der Befehl "python" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Der Befehl "python" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Der Befehl "python" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
E:\Python\whls\Kivy-1.9.2.dev0-cp35-none-win_amd64.whl konnte nicht gefunden werden
Running touchtracer demo...

---------- E:\PYTHON\ERROR.TXT: 1
Drücken Sie eine beliebige Taste . . .
```

System is Win10

which log i have to post?
the "msi_000-007 _JustForMe.log???

**Comment by KeyWeeUsr** [comment]
Maybe you have a little bit older version of installer. 3.5.2 is quite new, so it needs polishing, but still it works on win8.1 out of box. Try to get the [latest `kivy.bat`](https://raw.githubusercontent.com/KeyWeeUsr/KivyInstaller/master/kivy.bat).

Then try to look if you already have Python installed on your system (Win+X, Programs and features, look for "Python"). If it is, this might be the issue, because of the new installer since 3.5. I still didn't manage to push it to a state where it works only as unpacking, therefore it still uses registry. If Python is installed, remove it with these steps:

1. _repair_ python installation (to get files back, otherwise uninstall fails)
2. uninstall python

If you have both Python 3.5 removed and the latest `kivy.bat`, run the installation again, it should work as expected. If not, then send the `msi_000_core_JustForMe.log` and `msi_002_exe_JustForMe.log` files.

**Comment by Ch3fk0ch88** [comment]
Ok, thanks.
It works.

Greetings

**Comment by KeyWeeUsr** [comment]
What was the problem? Old version or installed Python?

**Comment by Ch3fk0ch88** [comment]
Well,
i did bouth at the same time.
So i dont know.

I downloaded the .bat from this github
https://github.com/KeyWeeUsr/KivyInstaller

so it should be the installed Python.

Greetings

**Comment by KeyWeeUsr** [comment]
Thanks for further info. Greetings :)

**Comment by Ch3fk0ch88** [comment]
I am frustrated,
after a reinstall of the complete System i want to install Kivy again and got the same error.
There was no Python installed and i used the newest bat.


[msi_000_core_JustForMe.txt](https://github.com/KeyWeeUsr/KivyInstaller/files/703030/msi_000_core_JustForMe.txt)
[msi_002_exe_JustForMe.txt](https://github.com/KeyWeeUsr/KivyInstaller/files/703031/msi_002_exe_JustForMe.txt)

**Comment by KeyWeeUsr** [comment]
I'm not really sure what's going on now. It behaves like it installs (somewhere), but at the end reports missing files (`E:\Python\*`). It might be worth looking into this folder:

    C:\Users\Bene\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Python 3.5\

if there isn't some `.lnk` file. If there is, right-click on it → Properties. What's the path in `Target`? Also, what happens if you try to install it to C:\ drive instead of E:\?

**Comment by Ch3fk0ch88** [comment]
Hi,
i will test it next week and give u a feedback.

**Comment by KeyWeeUsr** [comment]
@Ch3fk0ch88 Now it should be fixed for both admin and non-admin installation. Download the latest bat version (2.4) and it should work fine.
