### ISSUE TITLE
Suggestion: Make initial option selection clearer

### ISSUE THREAD

**Issue by Zen-CODE** [KeyWeeUsr/KivyInstaller#7]
The options you are given when you first run kivy.bat are quite cryptic. The implications of your selections are not really explained.

Specifically:
64bit detected, use 32bit instead? -> 64bit detected. Create a 32bit environment instead?
admin privileges? -> Does you app require admin privileges? (Ambiguity is "Do you have admin privileges?")
Install kivy? -> To where? Using kivy installer would kind of imply I want to install kivy, so I'm not sure what this means. Perhaps 'Install kivy into the local Python installation (otherwise self contained)?'

Or suchlike. It seems petty, but an it helps to make wording as clear and unambiguous as possible.

**Comment by KeyWeeUsr** [comment]
Closed by https://github.com/KeyWeeUsr/KivyInstaller/commit/18846d44af9e7aa689fcf4f2bdf6283b15d45435

The part about `install kivy` is rather meant as a "proceed" as the batch allows even to skip the part of installing kivy for various reasons (install of the interpreter alone, slow connection, custom way of installing, ...). I'm still thinking about moving it to the debug section instead of exposing it to the user directly, but for now I'll leave it be. Hopefully the options are clearer. :)
